- name: install slack
  become: True
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.3-amd64.deb

- name: install whatsapp
  become: True
  apt:
    deb: https://www.thefanclub.co.za/sites/all/modules/pubdlcnt/pubdlcnt.php?file=https://www.thefanclub.co.za/sites/default/files/public/downloads/whatsapp-webapp_1.0_all.deb&nid=200

- name: install yakyak for google chat
  command: snap install yakyak
  become: True

