#!/bin/bash

SESSION=tmux-prod-search-redis

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@10.80.90.169" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@10.80.90.170" C-m

# Attach to session
tmux attach-session -t $SESSION
