#!/bin/bash

SESSION=tmux-prod-mongo

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@TVL10DBH01PRD" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@TVL10DBH02PRD" C-m
tmux split-window -v
tmux send-keys "ssh bshah@TVL10DBH03PRD" C-m

# Attach to session
tmux attach-session -t $SESSION
