#!/bin/bash

SESSION=tmux-prod-mysql-dr

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@tvl16dbm01dr" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@tvl16dbm02dr" C-m

# Attach to session
tmux attach-session -t $SESSION
