#!/bin/bash

SESSION=tmux-ppe-admin-endecca

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@TVL10APP12PPE" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@TVL10APP03PPE" C-m
tmux split-window -v
tmux send-keys "ssh bshah@TVL10APP04PPE" C-m

# Attach to session
tmux attach-session -t $SESSION
