#!/bin/bash

SESSION=tmux-ppe-apache

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@TVL10WEB21PPE" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@TVL10WEB22PPE" C-m

# Attach to session
tmux attach-session -t $SESSION
