#!/bin/bash

SESSION=tmux-prod-kiosk

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@TVL10APP06PRD" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@TVL10APP07PRD" C-m

# Attach to session
tmux attach-session -t $SESSION
