#!/bin/bash

SESSION=tmux-prod-apache

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@TVL70WEB01PRD" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@TVL70WEB02PRD" C-m
tmux split-window -v
tmux send-keys "ssh bshah@TVL70WEB03PRD" C-m
tmux select-pane -t 0
tmux split-window -v
tmux send-keys "ssh bshah@TVL70WEB04PRD" C-m
tmux split-window -v
tmux send-keys "ssh bshah@TVL70WEB05PRD" C-m

# Attach to session
tmux attach-session -t $SESSION
