#!/bin/bash

SESSION=tmux-ppe-kiosk

tmux new-session -d -s $SESSION

tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh bshah@TVL10APP06PPE" C-m
tmux select-pane -t 1
tmux send-keys "ssh bshah@TVL10APP07PPE" C-m

# Attach to session
tmux attach-session -t $SESSION
