- name: create the wickes directory
  file:
    path: ~/wickes
    state: directory

- name: install wickes /etc/hosts file
  copy:
    src: wickes_hosts_file
    dest: /etc/hosts
  become: True

- name: install ssh to github on 443
  copy:
    src: ssh_config
    dest: ~/.ssh/config

- name: create the repos directory
  file:
    path: ~/wickes/repos
    state: directory

- name: git clone bitbucket idevops_ccoe repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/devops_ccoe/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - vm-image-factory
    - JenkinsPipelines
    - cloudshop

- name: git clone bitbucket devops repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/devops/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - infrastructure
    - hybris
    - core-ansible

- name: git clone bitbucket cloudshop repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/cloudshop/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - cloudshop

- name: git clone bitbucket micro-services repos
  git:
    clone: yes
    repo: "git@gitlab.com/wickesit/ccoe/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - microservices-infrastructure

