- name: create the bin directory
  file:
    path: ~/bin
    state: directory

- name: install wickes /etc/hosts file
  copy:
    src: wickes_hosts_file
    dest: /etc/hosts
  become: True

- name: install ssh to github on 443
  copy:
    src: ssh_config
    dest: ~/.ssh/config

  # - name: git clone bitbucket repos
  #   git:
  #   clone: yes
  #   repo: "git@bitbucket.org:travelodgical/{{ item }}.git"
  #   dest: "~/travelodge/bitbucket_repos/{{ item }}"
  #   update: yes
  # with_items:
  #   - devops
  #   - ng
  #   - ng-ansible-deploy
  #   - travelodgeecommerce
  #   - api-gateway
  #   - search
  #   - tl-web
  #   - suggestion
  #   - tripadvisor
