- name: create the wickes directory
  file:
    path: ~/wickes
    state: directory

- name: install wickes /etc/hosts file
  copy:
    src: wickes_hosts_file
    dest: /etc/hosts
  become: True

- name: install ssh to github on 443
  copy:
    src: ssh_config
    dest: ~/.ssh/config

- name: create the repos directory
  file:
    path: ~/wickes/repos
    state: directory

- name: create directory for smart-mocks
  file:
    path: ~/wickes/repos/smart-mocks
    state: directory

- name: git clone bitbucket smart-mocks repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/smart-mocks/{{ item }}.git"
    dest: "~/wickes/repos/smart-mocks/{{ item }}"
    update: yes
  with_items:
    - mock-notification-service
    - mock-payment
    - mock-smartfulfilment
    - mock-paypal

- name: git clone bitbucket devops_ccoe repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/devops_ccoe/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - vm-image-factory
    - JenkinsPipelines

- name: git clone bitbucket devops repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/devops/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - infrastructure
    - hybris

- name: git clone bitbucket cloudshop repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/cloudshop/{{ item }}.git"
    dest: "~/wickes/repos/{{ item }}"
    update: yes
  with_items:
    - cloudshop

- name: git clone the infrastructure artemis repos
  git:
    clone: yes
    repo: "https://github.com/travisperkins/artemis.git"
    dest: "~/wickes/repos/infrastructure/artemis"
    update: yes
- name: git clone the infrastructure cloudshop ansible repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/devops/cloudshop-ansible.git"
    dest: "~/wickes/repos/infrastructure/cloudshop-ansible"
    update: yes
- name: git clone the infrastructure core-ansible repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/devops/core-ansible.git"
    dest: "~/wickes/repos/infrastructure/core-ansible"
    update: yes
- name: git clone the infrastructure wickes non-production repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/secrets/wickes-non-production.git"
    dest: "~/wickes/repos/infrastructure/wickes-non-production"
    update: yes
- name: git clone the infrastructure wickes production repos
  git:
    clone: yes
    repo: "git@gitlab.com:wickesit/cloudshop/secrets/wickes-production.git"
    dest: "~/wickes/repos/infrastructure/wickes-production"
    update: yes

- name: install openfortigui
  become: True
  apt:
    deb: https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.7.2-3_bionic_amd64.deb

- name: wickes fortigate config
  copy: 
    src: "openfortigui_wickes.conf"
    dest: "~/.openfortigui/vpnprofiles/wickes.conf"

- name: dns resolver
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
  become: True
